<%
  require 'json'

  vcap_services = JSON.parse(ENV['VCAP_SERVICES'] || '{}')
  pg_service = vcap_services['postgresql-db']&.first
  creds = pg_service['credentials'] if pg_service

  puts "[DEBUG] VCAP_SERVICES: #{vcap_services}"
  puts "[DEBUG] PostgreSQL credentials: #{creds}"
%>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= creds['username'] %>
  password: <%= creds['password'] %>
  host: <%= creds['host'] %>
  port: <%= creds['port'] %>
  database: <%= creds['dbname'] %>
  search_path: <%= ENV['DATABASE_SEARCH_PATH'] || 'public' %>

development:
  <<: *default

production:
  <<: *default

