default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  url: <%= begin
    require 'json'
    vcap = JSON.parse(ENV['VCAP_SERVICES'])
    service = vcap.values.flatten.find { |s| s['label'] == 'postgresql' || s['name'] =~ /postgres/i }
    if service
      creds = service['credentials']
      "postgres://#{creds['username']}:#{creds['password']}@#{creds['host']}:#{creds['port']}/#{creds['dbname']}?options=-c%20search_path%3Ddocuseal"
    else
      raise "No PostgreSQL service found in VCAP_SERVICES"
    end
  rescue => e
    puts "Error parsing VCAP_SERVICES: #{e.message}"
    nil
  end %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
