disk:
  service: Disk
  root: <%= ENV['WORKDIR'] || '.' %>/attachments
  public: true


aws_s3:
  service: S3
  access_key_id: <%= JSON.parse(ENV['VCAP_SERVICES'])['objectstore'][0]['credentials']['access_key_id'] %>
  secret_access_key: <%= JSON.parse(ENV['VCAP_SERVICES'])['objectstore'][0]['credentials']['secret_access_key'] %>
  region: <%= JSON.parse(ENV['VCAP_SERVICES'])['objectstore'][0]['credentials']['region'] %>
  bucket: <%= JSON.parse(ENV['VCAP_SERVICES'])['objectstore'][0]['credentials']['bucket'] %>
  public: true
  upload:
    cache_control: 'public, max-age=31536000'

google:
  service: GCS
  credentials: <%= ENV['GCS_CREDENTIALS'] || '{}' %>
  project: <%= ENV['GCS_PROJECT'] %>
  bucket: <%= ENV['GCS_BUCKET'] %>
  public: <%= ENV['ACTIVE_STORAGE_PUBLIC'] == 'true' %>
  cache_control: "public, max-age=31536000"

azure:
  service: AzureStorage
  storage_account_name: <%= ENV['AZURE_STORAGE_ACCOUNT_NAME'] %>
  storage_access_key: <%= ENV['AZURE_STORAGE_ACCESS_KEY'] %>
  container: <%= ENV['AZURE_CONTAINER'] %>
  public: <%= ENV['ACTIVE_STORAGE_PUBLIC'] == 'true' %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
  public: true
